info:
  title: Abc
  version: 1.0.0
  x-lastModified: Jun 07, 2017 23:07PM PST
paths:
  /test:
    post:
      parameters: []
      produces:
      - application/json
      responses:
        "200":
          description: Success response
swagger: "2.0"
